### ISSUE TITLE
Level builder - automatic camera setup

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#12]
For now we select the options manually. Basically we need to force the camera to be orthographic and with a certain size and clipping plane.

**Comment by OlafSzmidt** [comment]
There's code written for this in the `UnityProject/Assets/Editor/LevelBuilder/GUI/LevelBuilderWindow.cs` file in the `SetUp()` method. It works as it is, but only when the Level Builder window is opened via the GUI. We need to change this so that it's called along with Unity somehow.

The branch is _yet_ to be merged.

**Comment by OlafSzmidt** [comment]
Linked to #35.

**Comment by OlafSzmidt** [comment]
Fixed with #35 and more specifically https://github.com/ocadotechnology/aimmo-unity/commit/1440286ebb83982f549c530e1b4b2ba4d4e5a0cd.
