### ISSUE TITLE
Level builder - find a better way to pass around types

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo-unity#44]
We hold a type in the `SpriteGeneratorBuilder`. The way it's done, it works but it is a bit hacky and is hard to understand. Also, leads to lines of code such as line 144 in `SpriteGeneratorBuilder`. We should find an alternative way. @danalex97 might have some ideas.

**Comment by danalex97** [comment]
Initially, I tries working with generics, but encountered various problems; thus, we use reflection. For some reason keeping the types without the assembly reference was not working for me. If you can find a workaround to actually use `Type` instead of `string` to store the types, that would solve this. 

Also, [this](https://stackoverflow.com/questions/12306/can-i-serialize-a-c-sharp-type-object) might be of interest. 

Another solution(which is probably simpler) is to make a class that has all the responsibility related to the types and that can be serialized. (basically a class like 'Type' that also keeps the name of the assembly and can be serialized)

**Comment by mrniket** [comment]
We aren't doing this anymore, not relevant.
