### ISSUE TITLE
Level Builder - Unable to generate two sprites of the same type

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#51]
Unless the sprite is renamed in the hierarchy, we can't import the same sprite for the second time right now.

**Comment by ramonfmir** [comment]
That seems to be right. We were only testing it with copy and paste. You could just generate a hash and append it to the name. Be careful about how that might affect the exporting bit.

**Comment by danalex97** [comment]
@OlafSzmidt  This is just because the default name that the object gets when the sprite is imported. We tried to solve this before by adding a name field in the UI, which worked. Another idea is to have a counter that gets auto-incremented and appended to name. An uglier idea is to generate random names each time.
