### ISSUE TITLE
Level Builder - Generating obstacles not seen as a modification by unity

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo-unity#52]
Generating obstacles makes them appear on the scene we are working on right now, but if you change scenes (note: nothing to save at this point according to Unity) then come back to the original one, the sprite will be gone and neither on screen or in the hierarchy.

If you move the sprite by mouse (not by WSAD from the Level Builder), unity sees a change, you can then save the scene and the object will persist.

**Comment by OlafSzmidt** [comment]
@danalex97 Any idea on this?

**Comment by ramonfmir** [comment]
That is strange. We don't explicitly save the scene anywhere in the code but I think @danalex97 made sure that all the data we needed was tagged as serialisable so that Unity could save it. That is why many things have `[SerializableField]` in front.

As an idea, this might have to do with a comment I made in #35 since the `ObjectController` still holds the level builder context. I don't think that should interfere with saving the scene but is definitely somehow related to it since `ObjectController` is the script used to move the game objects.

**Comment by danalex97** [comment]
@ramonfmir  That is connected to JSON serialization as we want the data to persist. I think @OlafSzmidt is fixing the issue.

It is something related to dirty bits. The objects/scene are not marked dirty so they don't get saved. When we changed the scene the objects would just get unloaded and then lost.  Since we also had different unity versions(with different editors handling dirty bits) the bug never appeared for me. :(

**Comment by OlafSzmidt** [comment]
Nothing to do with `[SerializableField]`I'm afraid. So according to @danalex97, this was not an issue on your guys' Unity version. On mine it was, even when I rolled the commits back to September 4. 

The issue turned out to be in the fact that Unity needs to have an indication of a "dirty" scene by code if scripts instantiate game objects. Solution is in `EditorSceneManager.MarkAllScenesDirty()` or one of the similar methods.

**Comment by danalex97** [comment]
For future reference, adding delegates/callbacks to [this events](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html) might be useful.

**Comment by OlafSzmidt** [comment]
This is fixed for generating new levels, but still needs to be implemented when you are moving between levels on the dropdown menu.

**Comment by ramonfmir** [comment]
Fair enough @danalex97, true that, it has nothing to do with `[SerializableField]`.

@OlafSzmidt does that mean that when you switch between levels the scenes don't get saved?

**Comment by OlafSzmidt** [comment]
Yes, exactly @ramonfmir. It was fixed in my pull request but not for all cases so keeping this open.

**Comment by ramonfmir** [comment]
No problem comrade @OlafSzmidt
